[project]
name = "fast-api-web-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rudra1404-shah", email = "shahrudra1404@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
fast-api-web-application = "fast_api_web_application:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
